### ISSUE TITLE
:bulb: Feature request > Be able to choose any locally installed model :pray: 

### ISSUE THREAD

**Issue by adriens** [BruceMacD/chatd#1]
Currently, it seems like we cannot choose any locally installed model : 

- Is it possible ?
- Would it be possible ?

**Comment by BruceMacD** [comment]
Hi @adriens, thanks for the feature request. It is currently possible, but a bit hidden. 

The model can be specified by downloading [Ollama](ollama.ai). If Ollama is running when chatd starts a settings button will be displayed in the top right corner of the screen which allows specifying a model by name.

I'll document this somewhere.

<img width="912" alt="Screenshot 2023-11-02 at 16 17 48" src="https://github.com/BruceMacD/chatd/assets/5853428/74f45dc1-bcd2-43e1-95f0-d0a432673154">

<img width="912" alt="Screenshot 2023-11-02 at 16 17 56" src="https://github.com/BruceMacD/chatd/assets/5853428/9bbb46d0-81cf-48c2-a29f-a3b9260d85c8">

**Comment by basillicus** [comment]
I believe that is not working on Linux? I have ollama running on the localhost http://127.0.0.1:11434/ however everytime I run chatd it automatically starts downloading an LLM. 

My ollama mistral model is working, because it runs in the terminal, however Chatd is not recognising ollama is up.

**Comment by BruceMacD** [comment]
@basillicus Those steps are correct. I've seen some reports of instances in Linux where Ollama wasn't accessible on 127.0.0.1, I'm gonna take a look this and get back to you.

**Comment by adriens** [comment]
Hey @BruceMacD , thanks a lot fot the tricks :pray:

**Comment by basillicus** [comment]
Hi @BruceMacD , I believe the communication is actually correct. 

If I run `journalctl -u ollama -f` to see the ollama's log on the fly and execute chatd, I can see is ollama who is downloading the model. 

```

Nov 04 12:48:32 cirujano ollama[3473]: [GIN] 2023/11/04 - 12:48:32 | 200 |      54.606µs |       127.0.0.1 | GET      "/"
Nov 04 12:48:34 cirujano ollama[3473]: 2023/11/04 12:48:34 download.go:127: downloading 6ae280299950 in 64 64 MB part(s)
Nov 04 12:48:54 cirujano ollama[3473]: [GIN] 2023/11/04 - 12:48:54 | 200 | 22.413264133s |       127.0.0.1 | POST     "/api/pull"
```

So maybe may it be related to the name of the model I create with ollama? Sorry I am still new in this LLM world

**Comment by BruceMacD** [comment]
Thanks for the update basillicus, that explains it. I didn't make the custom model loading with models that aren't available locally already in mind. I'll spin that out into a different issue.

It will work better if you run `ollama pull <model name>` in a terminal and download the model before switching it in chatd for the time being.

**Comment by BruceMacD** [comment]
Moved a better "new model download" experience to a new issue. Resolving this one for now as it is generally possible to run custom LLMs.
