### ISSUE TITLE
UI launches with browser dev tools at the side

### ISSUE THREAD

**Issue by danja** [BruceMacD/chatd#11]
For me on launch, the Electron BrowserWindow is split, see attached. It's *possible* (but very unlikely) it's picking up local settings, I was playing with Electron not long ago, but I didn't go anywhere near showing dev tools.   

![Screenshot from 2023-11-06 21-44-09](https://github.com/BruceMacD/chatd/assets/2303/03b1ff67-4f7b-40cb-b50c-e2f4607f1e39)

**Comment by BruceMacD** [comment]
Hi @danja, are you building from source by chance? The app displays this when its not packaged since that is considered "development mode".

**Comment by danja** [comment]
Ah, ok - you got it, thanks. No issue.
