### ISSUE TITLE
question about the project...

### ISSUE THREAD

**Issue by torik988** [BruceMacD/chatd#27]
hi i'm searching for a tool using ollama and Llm in general that allow me to search from a prompt some local files and sumarise and give them directly to the user. the goal is th help the user to find specific company infos from the files that he have acces. most llm will imaginate so i was wondering if chatd was able to do this... tanks 
Nice day

**Comment by BruceMacD** [comment]
Hi @torik988, chatd is part of the way to this goal, but it can only handle 1 file at a time at this point.
