### ISSUE TITLE
Feature request > Cuda Support -config options

### ISSUE THREAD

**Issue by cibernicola** [BruceMacD/chatd#3]
I love the concept of starting an application and getting to work with it, I really do.
Maybe I haven't seen it or maybe it's missing, but I think it would be highly interesting if there were configuration options and even templates, as well as CUDA support to improve inference speed.
At the moment it looks more than interesting. Maybe you could talk to LM Studio and join forces?

**Comment by BruceMacD** [comment]
Thanks for the feedback @cibernicola. This is actually another hidden feature right now that can be enabled by running your own instance of [Ollama](https://ollama.ai), which chatd will automatically connect to on start-up. Ollama will automatically make use of an nvidia gpu on Linux, with Windows GPU support coming in the future.

**Comment by BruceMacD** [comment]
Added GPU configuration to the docs, so resolving this issue for now. In the future I may package in GPU support, but for the time being I'm leaving it optional to keep the size of the application a bit smaller.
