### ISSUE TITLE
404 endpoint not available

### ISSUE THREAD

**Issue by dnovacik** [BruceMacD/chatd#31]
Hi, you've made recent commits where you switch from /api/generate endpoint to /api/chat endpoint. When I run the packed executables (outside of chatd) they do not provide the /chat endpoint. When I install ollama to my WSL via the sh from ollama page, it provides the /chat endpoint. Is there a difference between running it inside WSL/spawning a child process via node? Or a version difference? Thanks!

**Comment by BruceMacD** [comment]
@dnovacik thanks for bringing this to my attention. I just released a new version with the most recent version of Ollama packaged in. Your issues should be resolved now by updating.
