### ISSUE TITLE
100k pdfs?

### ISSUE THREAD

**Issue by MatteoRiva95** [BruceMacD/chatd#32]
Hello everyone,

It is not a proper issue, just a few questions.
Is it possible to use chatd with 100k english PDFs? Or it is too much data?
If I can use it, how can I load them with Linux terminal? 

Thank you so much in advance!

**Comment by BruceMacD** [comment]
Hi @MatteoRiva95, as it stands right now this wouldn't be possible. Chatd is storing the files in memory when they are open, so I'd need to add some more long term storage for this.

I have #8 open for reading multiple files if you'd like to track more progress on it.
