### ISSUE TITLE
Is there a web version

### ISSUE THREAD

**Issue by alfi4000** [BruceMacD/chatd#39]
Is there a web version because I run all my ai stuff on my server and I access it from my desktop!?

**Comment by BruceMacD** [comment]
Hi @alfi4000 this project is focused on being a desktop application, demonstrating how Ollama can be packaged. 

For some options on desktop apps this is a good place to start:
https://github.com/ollama/ollama?tab=readme-ov-file#web--desktop

open-webui has some "chat with documents" features also, I think it will be what you are looking for:
https://github.com/open-webui/open-webui

**Comment by alfi4000** [comment]
Ok
