### ISSUE TITLE
Unable to load dynamic server library

### ISSUE THREAD

**Issue by Tri0L** [BruceMacD/chatd#46]
Apple M3 Max

```Error: Unable to load dynamic library: Unable to load dynamic server library: dlopen(/var/folders/5j/k79qzwzj79zccrv78q7yc3yh0000gn/T/ollama1325625138/metal/libext_server.dylib, 0x0006): tried: '/var/folders/5j/k79qzwzj79zccrv78q7yc3yh0000gn/T/ollama1325625138/metal/libext_server.dylib' (code signature in <5A0BFDE3-DAFF-3CDC-88E1-EB69C3900B6B> '/private/var/folders/5j/k79qzwzj79zccrv78q7yc3yh0000gn/T/ollama1325625138/metal/libext_server.dylib' not valid for use in process: mapping process and mapped file (non-platform) have different Team IDs),```

**Comment by trajche** [comment]
Same issue on Apple M3 Pro.

**Comment by hhamud** [comment]
Same issue on Apple M1 Pro.

**Comment by BruceMacD** [comment]
Hey everyone, thanks for the reports. I believe this was a bug in the packaged ollama runner which should be fixed now in v1.1.1`. If anyone else still experiences this please let me know.
